Controlador conseguirExperiencia mediante Id
SerxoLaxe/proyectoHAB pull request #9
Opened 2021-08-21 09:19 UTC by cristinadominguezgomez

2021-08-21 11:17 UTC, SerxoLaxe requested changes
Hola Cristina. El controlador buscarExperiencias está casi perfecto, le falta simplificar la query y estar formateado, que es cosa de que pulses Ctrl + Shift + I en VScode.  Al controlador conseguirExperiencia.js le sobra la comprobación de si la experiencia existe. Cambia eso y hacemos merge.

2021-08-21 11:17 UTC, SerxoLaxe commented on aplicacion/backend/controllers/experiencias/conseguirExperienciaID.js
> +
Aquí falta establecer el código de estado de respuesta correcta, como hiciste con el otro controlador
```suggestion
res.statusCode = 200;
```

2021-08-21 11:17 UTC, SerxoLaxe commented on aplicacion/backend/DB/initDB.js
> +            conexion.release();
Seguro que fue sin querer pero aquí añadiste unos cuantos espacios.

2021-08-21 11:17 UTC, SerxoLaxe commented on aplicacion/backend/controllers/experiencias/buscarExperiencias.js
>   * buscarExperiencias() toma los parámetros definidos en la query ylos usa para buscar coincidencias en la tabla experiencias.❌
Acuerdate de ponerle el pulgar arriba :+1:  cuando termines el controlador, tanto en el propio controlador como en la llamada a esta en server.js

2021-08-23 10:06 UTC, oscarb65 commented
Vale

2021-08-23 20:45 UTC, SerxoLaxe commented
Voy a hacer merge y luego elimino el bloque de código que sobra del controlador.

2021-08-23 20:45 UTC, merged

2021-08-29 08:03 UTC, cristinadominguezgomez commented on aplicacion/backend/controllers/experiencias/conseguirExperienciaID.js
> +        }
Claro pero eso se suele hacer la segunda vez que se repite el código y esta es la primera vez

2021-08-29 08:03 UTC, cristinadominguezgomez commented on aplicacion/backend/controllers/experiencias/buscarExperiencias.js
> +
Porque va a hacer falta hacerlo así cuando hagamos el JOIN a las otras tablas